inCARDIO-Dashboard-Selenium-test job:
  image: maven:3.8.5-openjdk-17
  tags:
    - testing-runner
  script:
    - echo "test123123"

build image:
    image: docker
    tags:
      - testing-runner
    services:
      - docker:dind
    script:
      - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
      - docker build -t $CI_REGISTRY_IMAGE .
      - echo $CI_REGISTRY_IMAGE
      - docker push $CI_REGISTRY_IMAGE
      - docker run -dt --name testing sdx-testing-projects