version: "3.9"
services:

  chrome:
    image: selenium/standalone-chrome
    container_name: web-chrome



  testrunner:
    build: .
    environment:
      SELENIUM_WEBDRIVER_URL: http://chrome:4444
  #  volumes:
   #   - type: bind
   #     source: ./input
    #    target: ./input
    depends_on:
      chrome:
        condition: service_started