version: "3.9"
services:

  chrome:
    image: selenium/standalone-chrome
    container_name: web-chrome
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444"]
      interval: 10s
      timeout: 10s
      retries: 6

  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20230221
    volumes:
      - ./videos:/videos
    depends_on:
      testrunner:
        condition: service_healthy

    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4


  testrunner:
    build: .
    environment:
      SELENIUM_WEBDRIVER_URL: http://chrome:4444
    volumes:
      - type: bind
        source: ./input
        # XXX /testrunner hardcoded in the dockerfile instead testrunner-application should allow us to configure where the input path is
        target: /testrunner/input
    depends_on:
      chrome:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3333" ]
      interval: 10s
      timeout: 10s
      retries: 6
