version: "3.9"

x-inSuiteServerURL: &inSuiteServerURL
  #ICN_URL needs to keep the name for the file-forwarder to work with this
  ICN_URL: "https://cnx12003dp.hub.doc-cirrus.com"

services:

  file_forwarder:
    image: gitlab.semdatex.de:5005/semdatex/sdx-file-forwarder:latest
    container_name: "out"
    ports:
      - 2200:2200
    environment:
      NAME: out
      FORWARD_DQV_MSGS: on
      DQV_TOKEN: -*-
      DQV_URL: -*- (e.g. https://dcm1al4fpj.hub.doc-cirrus.com)
      DQV_FILTERING: on
      DQV_LOCATION_ID: -*-
      DQV_USER_ID: -*-
      DQV_DEVICE_TYPE: -*-
      FORWARD_ICN_MSGS: "on"
      ICN_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.IjdXNGM2OWpmRlNsVU5xR0xYaEl6RWE4YWZPdTI5ZlpQYkZRQk5hWEtnT3VCQVRYN3BqWUxIcHdjRk5mYnFWb3Ii.dB2wTg0fMAuRhGNk8YnVAsy7rGLFy2E2MSPjk0U_iB4
      <<: *inSuiteServerURL
      ICN_FILTERING: on
      ICN_LOCATION_ID: 000000000000000000000001
      ICN_DEVICE_TYPE: Abbott
      DEV_MODE: on
      HOST: hostname
    volumes:
      - fileforwarder:/mnt/out

  testrunner:
    build: .
    env_file:
      lambdatest.env
    environment:
      LAMBDATEST_PLATFORM: "Windows 10"
      LAMBDATEST_BROWSER_NAME: "Chrome"
      LAMBDATEST_BROWSER_VERSION: "100.0"
      LAMBDATEST_VERSION: "4.0.0"
      SELENIUM_WEBDRIVER_URL: "https://hub.lambdatest.com/wd/hub"
      <<: *inSuiteServerURL
    volumes:
      - fileforwarder:/input
      - test_result_logs:/logs
    depends_on:
      file_forwarder:
        condition: service_started

volumes:
  fileforwarder:
  test_result_logs: